name: Continuous_Activity_Check
on:
  push:
  schedule:
    - cron: '0 0 * * *' # 每天北京时间早上8点自动运行一次
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Heartbeat
        run: echo "Activity verified at $(date)"
